name: youzi
version: 1.0.0

# 环境配置
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

# Spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# 日志配置
logging:
  config: classpath:logback.xml



